version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      POSTGRESPORT: 5432
      POSTGRESUSER: postgres
      POSTGRESPASSWORD: postgres
      POSTGRESDATABASE: darkify
    depends_on:
      - db

  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: darkify
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
