name: ESLint Check

on:
  pull_request:
  push:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install frontend dependencies
        run: |
          cd web
          npm ci

      - name: Run ESLint for frontend
        run: |
          cd web
          npm run lint

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run ESLint for backend
        run: |
          cd backend
          npm run lint
  ts-frontend:
    name: TS Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install frontend dependencies
        run: |
          cd web
          npm ci

      - name: Run ESLint for frontend
        run: |
          cd web
          npm run test:typescript

  ts-backend:
    name: TS Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run ESLint for backend
        run: |
          cd backend
          npm run test:typescript
